name: Daily Ecobalyse Monitor

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run script
        run: python script.py
